### PR TITLE
✨ Allow to set additional fsspec kwargs for cloud instances

### PR DESCRIPTION
**Pull request by Koncopd**
subj

### CODE REVIEW

**Comment by Koncopd** [comment]
It looks like there are problems wiht CI instances related to migration. On some instances lnschema-core is new and on some it is old, this is why CI fails.

**Comment by falexwolf** [comment]
You can resolve this in two ways:
1. Either delete the CI instance
2. Or migrate the CI instance

**Comment by falexwolf** [comment]
Always feel free to delete the CI instances!

Another important thing is that the CI runs run on the latest version of lamindb. Clearing the cache often helps with that.

**Comment by falexwolf** [comment]
I hope we'll get this under better control soon.

**Comment by Koncopd** [comment]
Ok, understood.

**Comment by Koncopd** [comment]
@falexwolf this is rather a quick hack.
```
lndb.setup.storage("s3://some-bucket")
lndb.setup.settings.storage.set_fs_kwargs(profile="some_profile", cache_regions=True) # any fsspec args
```
also can be used after `init` and `load` of postgres intstances.

It is quite complicated to add this on init, save it etc (especially in CLI).

This should do the trick for now.

**Comment by falexwolf** [comment]
I like this!

**Comment by falexwolf** [comment]
There is no need at all to do this during `init`! I prefer that it's called after, the way you did it!

**Comment by falexwolf** [comment]
There is also no need to call it on the CLI. This is a highly configured case, we can ask users to use the Python API.

**Comment by falexwolf** [comment]
We just need to add this documentation within the `set-storage` notebook, so that users can see it.

**Comment by falexwolf** [comment]
Ohhhhh!

**Comment by falexwolf** [comment]
I thought you went to bed! I just did a small refactor. Can you check?

**Comment by falexwolf** [comment]
The refactor is just meant to be small simplification on the user end that allows them to pass it directly to `ln.setup.set.storage(root, **fs_kwargs)` rather than having to call another function.

**Comment by Koncopd** [comment]
Makes making a test a bit more complicated though.

**Comment by falexwolf** [comment]
Why not just adding the kwargs to `add_storage` in the test? Is that a problem?

**Comment by falexwolf** [comment]
Ah, damn it, made the function private in the last minute. Will you fix or shall I? Don't want to cause conflicts.

**Comment by Koncopd** [comment]
I did, but we need to check the kwarg also **before** setting.

**Comment by Koncopd** [comment]
I will change.

**Comment by Koncopd** [comment]
The problem with with approach is that sometimes setting some additional fsspec kwargs could be also needed for sqlite cloud instances on `init`.

**Comment by falexwolf** [comment]
Then shall we just make `set_fs_kwargs` public again? And Thomas can just use the simplified way of passing to `set.storage` and the use case that you're alluding to can work through `Storage.set_fs_kwargs`?

**Comment by falexwolf** [comment]
I'm not so worried about sqlite cloud instances right now, though. Because nobody asked for it (of course it's good that you think for the future and want to minimize technical debt!).

**Comment by Koncopd** [comment]
`set_fs_kwargs`  won't help sqlite instances. On `init` they will need all kwargs set already to have proper access rights etc.

**Comment by Koncopd** [comment]
Can be merged, i guess.

**Comment by falexwolf** [comment]
Great! Then let's merge!

**Pull request merged**
